name: run tests

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: pyth install
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install depend
        run: pip install -r requirements.txt

      - name: run
        run: pytest -q
  

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Docker image
        run: docker build -t app_load:latest .

      - name: save docker image
        run: docker save app_load:latest -o mm_app.tar

      - name: Fix permission
        run: sudo chmod 644 mm_app.tar
      
      - name:  Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "mm_app.tar"
          target: "~/NikitinT/deploy"

      - name:  Copy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
            mkdir NikitinT
            cd ~/NikitinT
            mkdir -p deploy
            cd deploy

            echo "Loading Docker image..."
            docker load -i mm_app.tar

            echo "stopping old container..."
            docker rm -f mm_app || true

            echo "starting new container"
            docker run -d --name mm_app -p mm_app:latest

            echo "Deployment finished!"

